### ISSUE TITLE
Add MySQL as a backend to store fixity records

### ISSUE THREAD

**Issue by dbrower** [ndlib/bendo#10]
The background process currently uses an embedded SQL engine, provide option to use MySQL for production instances.

Also change the SQL code to append records of results instead of updating records in place.

**Comment by dbrower** [comment]
The code is there. It needs to be configured in the deploy.

**Comment by msuhovec** [comment]
Created https://jira.library.nd.edu/browse/SYSADMIN-1430 for preprod and prod DBs

**Comment by msuhovec** [comment]
| id9012x       | 2016-04-13 23:59:52 | scheduled |       |
| id9013x       | 2016-08-03 18:38:39 | scheduled |       |
| id9014x       | 2016-09-06 22:55:20 | scheduled |       |
| id9015x       | 2016-09-22 11:03:45 | scheduled |       |
| id9016x       | 2016-07-10 02:17:04 | scheduled |       |
| id9017x       | 2016-09-06 23:11:23 | scheduled |       |
| id9018x       | 2016-08-07 00:39:06 | scheduled |       |
| id9019x       | 2016-09-08 17:26:39 | scheduled |       |
| id9020x       | 2016-03-20 20:46:17 | scheduled |       |
| id9021x       | 2016-05-09 14:44:52 | scheduled |       |
| id9022x       | 2016-10-31 02:42:53 | scheduled |       |
| id9023x       | 2016-05-12 23:15:15 | scheduled |       |
| id9024x       | 2016-03-15 00:57:29 | scheduled |       |
| id9025x       | 2016-09-09 07:51:51 | scheduled |       |
| id9026x       | 2016-06-30 15:24:04 | scheduled |       |
| id9027x       | 2016-07-21 01:23:19 | scheduled |       |
| id9028x       | 2016-09-29 15:12:55 | scheduled |       |
| id9029x       | 2016-03-02 22:13:18 | scheduled |       |
| id9030x       | 2016-06-02 16:54:19 | scheduled |       |
| id9041x       | 2016-04-09 20:59:53 | scheduled |       |
| id9042x       | 2016-07-23 09:50:39 | scheduled |       |
| id9043x       | 2016-09-27 06:34:05 | scheduled |       |
| id9099x       | 2016-03-19 18:35:14 | scheduled |       |
| bubba         | 2016-08-06 08:06:45 | scheduled |       |
| pup1234       | 2016-04-21 21:18:25 | scheduled |       |
| 2Fkh04dn42491 | 2016-10-11 01:15:34 | scheduled |       |
| 2Fkh04dn42492 | 2016-09-14 10:56:26 | scheduled |       |
| 2Fkh04dn42493 | 2016-05-14 20:09:58 | scheduled |       |
+---------------+---------------------+-----------+-------+
10037 rows in set (0.02 sec)

mysql>

**Comment by msuhovec** [comment]
It's working on staging.

**Comment by dbrower** [comment]
This is great! ...We have 10037 items in staging?!?

**Comment by msuhovec** [comment]
You must have bstress stuff in there, still

**Comment by dbrower** [comment]
yeah. maybe we should create a way to purge everything from bendo on the staging machines?
