### ISSUE TITLE
bclient needs a resume strategy

### ISSUE THREAD

**Issue by msuhovec** [ndlib/bendo#106]

**Comment by msuhovec** [comment]
Not sure yet exatly what the strategy will be.

**Comment by dbrower** [comment]
This is just speculation. Feel free to try something else.

Uploaded files in bendo can have labels attached, and they can be searched for by label.

So, given an item id of `XXX` and a file of size N with the md5sum `MMM`, the steps would be:

1. See if the file has already been uploaded:

        GET /upload?label=XXX&label=MMM

1. If the result is empty jump forward to step [newfile].
1. So the result is non-empty. say `file1` is one of the files returned. (based on how we determine the labels, there should never be more than one file returned. If so...?). See how much of the file has been uploaded so far: 

        GET /upload/file1/metadata

1. If the size is equal to N this file is uploaded. Stop.
1. The file is not uploaded. Seek to the number of bytes already in bendo, and start uploading chunks from there. Stop.
1. **[newfile]** Upload the first chunk and receive a random file name
1. Set the correct labels on that file name:

        PUT /upload/file1/metadata
        body: {"label": [ "XXX", "MMM" ]}  (This needs to be played around with...)

1. Continue uploading chunks to the file.

**Comment by dbrower** [comment]
Don't forget to set the `Accept-Encoding` header to be `application/json` for the `GET` requests.

**Comment by msuhovec** [comment]
I opted, rather than the labels, to use a known fileId format of itemid-md5sumoffile
{"ID":"qwerty6-98a69616d710c684392e4c508c85abca","Size":1750204139,"NFragments":167,"Created":"2016-03-09T15:28:31.849445711-05:00","Modified":"2016-03-09T15:29:01.628341914-05:00","Creator":"","Labels":null,"MD5":null,"SHA256":null,"Extra":""}

**Comment by msuhovec** [comment]
OK, I think this is working!

Let's take a 3GB file,  3023228928 bytes, with md5sum 98a69616d710c684392e4c508c85abca (this becomes mKaWFtcQxoQ5LkxQjIWryg== in base64)

It normally takes around 53 seconds to upload a 3GB filer to bendo.

We'll start the upload, and cntl-C out after 25 seconds or so:
bash-3.2$ bclient -v -token W8oROuHnDl9GeIsSbzzumeqnDMdy0NIY upload qwerty8  testdup3.cdr

Local Files:
File: testdup3.cdr md5 98a69616d710c684392e4c508c85abca

Files to Upload:
File: testdup3.cdr md5 98a69616d710c684392e4c508c85abca
Start Upload of qwerty8-98a69616d710c684392e4c508c85abca/testdup3.cdr at offset 0, size 3023228928, chunkSize 10485760 at 2016-03-09 16:02:34.205868233 -0500 EST
^C

Now we'll try to upload the file again- notice that the upload starts at offset 1519107819
bash-3.2$ bclient -v -token W8oROuHnDl9GeIsSbzzumeqnDMdy0NIY upload qwerty8  testdup3.cdr

Local Files:
File: testdup3.cdr md5 98a69616d710c684392e4c508c85abca

Files to Upload:
File: testdup3.cdr md5 98a69616d710c684392e4c508c85abca
Start Upload of qwerty8-98a69616d710c684392e4c508c85abca/testdup3.cdr at offset 1519107819, size 3023228928, chunkSize 10485760 at 2016-03-09 16:03:13.299864366 -0500 EST
Finished Upload of qwerty8/testdup3.cdr in 25.376049989 seconds

 Transaction id is /transaction/ktjpab
Waiting on ktjpab:........
Finished

The second upload took 25 seconds, which is what we'd expect for the remaining 1.5GB

A http://libvirt9.library.nd.edu:14000/item/qwerty8 reveals 

{"ID":"qwerty8","MaxBundle":1,"Blobs":[{"ID":1,"SaveDate":"2016-03-09T16:03:36.910948163-05:00","Creator":"bclient","Size":3023228928,"Bundle":1,"MD5":"mKaWFtcQxoQ5LkxQjIWryg==","SHA256":"s3i3lRcvXluRs09dDo2hceaH2+dGOQdnkOvreU52IJE=","DeleteDate":"0001-01-01T00:00:00Z","Deleter":"","DeleteNote":""}],"Versions":[{"ID":1,"SaveDate":"2016-03-09T16:06:12.200327323-05:00","Creator":"bclient","Note":"","Slots":{"testdup3.cdr":1}}]}

The md5 sum of mKaWFtcQxoQ5LkxQjIWryg== is correct.

**Comment by dbrower** [comment]
Excellent!

I'm surprised at how simple the retry logic from using the "itemid-md5sum" formatted upload file ids.
