### ISSUE TITLE
Add configuration file option

### ISSUE THREAD

**Issue by dbrower** [ndlib/bendo#107]
This is pushed mainly by not wanting to expose the database password on the command line. The main command `cmd/bendo` should read the file and fit it into the the RESTServer structure. So the main server code does not need to know about the config file at all.

The only requirement I have on the config file syntax is that it support comments. This rules out JSON.

Should the access tokens also be loaded from the config file? Or does it make sense to keep them separate?

**Comment by msuhovec** [comment]
I think this is done!
