### ISSUE TITLE
bendo DB changes

### ISSUE THREAD

**Issue by msuhovec** [ndlib/bendo#113]
rename the id column in both fixity and items. create a primary key id for each table.

I'm guessing that will look like this:

fixity

id int auto_increment, primary_key
item varchar(255),
scheduled_time datetime,
status varchar(32),
notes text)`,

items 
                id int autoincrement primary_key,
                item varchar(255),
                created datetime,
                modified datetime,
                size int,
                value text)`,

**Comment by msuhovec** [comment]
The DB migration, done manually, is this:

use bendo_staging;
alter table fixity change id item varchar(255);
alter table items; change id item varchar(255);
alter table fixity add column id int primary key auto_increment first;
alter table items add column id int primary key auto_increment first;

**Comment by dbrower** [comment]
I think this is related commit d5f8621bf63a64b65915a2af19f60bf3ea71fdeb
Can this issue be closed?
