### ISSUE TITLE
HEAD support for /item/:id/*path

### ISSUE THREAD

**Issue by dbrower** [ndlib/bendo#117]
Add support for a `HEAD` request to the `/item/:id/*path` route. The head route should return all the headers the `GET` route does. The `HEAD` route different from `GET` in two ways:

 * The `HEAD` does not return any content. (this is normal for a HEAD request)
 * The `HEAD` method will *not* recall or cache a blob from tape if it is not already in the cache.

Also, the implement the `X-Cached` header. Set the header to "1" if the blob was already in the cache. Set the header to "0" if the blob was *not* already in the cache.

**Comment by msuhovec** [comment]
I assumed, for a head request request, you'd leave out the "Content_Length" header- if that's incorrect, let me know.

**Comment by msuhovec** [comment]
The QL unit tests fail on my machine. Not sure why.

**Comment by dbrower** [comment]
I think this is finished.
