### ISSUE TITLE
deleted blob remains in blob cache

### ISSUE THREAD

**Issue by msuhovec** [ndlib/bendo#120]
an existing blob that is deleted with a 'delete' command via POST /item/:itemid/transaction remains in the blob cache (if it has been cached) and will be returned from the cache by a GET /item/:itemid - see 
https://github.com/ndlib/bendo/blob/master/server/server_test.go#L86-L97

**Comment by msuhovec** [comment]
I commented out the test- it is part of  existing test suite that worked before caching was introduced.

**Comment by dbrower** [comment]
Thanks for making this ticket. I saw the commented out test and forgot to make one.
