### ISSUE TITLE
Add user token verification

### ISSUE THREAD

**Issue by msuhovec** [ndlib/bendo#26]

**Comment by dbrower** [comment]
This issue is blocked pending details on the user auth token provided by Cogitate.

**Comment by dbrower** [comment]
There are some PR including the functionality: #47 and #42.
There is a way to configure it on the command line.

The token files need to be configured in the deployment.

**Comment by dbrower** [comment]
This is finished when #63 is.

**Comment by dbrower** [comment]
I think this is done?
