### ISSUE TITLE
Send file checksums on download

### ISSUE THREAD

**Issue by dbrower** [ndlib/bendo#32]
unsure of the header to use. It would be in the bendo API document.

**Comment by dbrower** [comment]
The api doc gives `X-Content-Sha256` as the header. And the hash is represented as a base16 (hex) string.

**Comment by msuhovec** [comment]
Here's what it looks like:

  GET  http://127.0.0.1:14000/item/id2016apr04/adb.log

    Status Code: 200 OK
    Content-Length: 168
    Content-Type: text/plain; charset=utf-8
    Date: Tue, 05 Apr 2016 18:32:59 GMT
    Etag: 1
    Location: /item/id2016apr04/@blob/1
    X-Content-Sha256: a94c75fdf3419a2ea000f929420086d30fc157ff7b8056420b29d9b7f54cbd2e
