### ISSUE TITLE
Server should exit on receiving signal

### ISSUE THREAD

**Issue by dbrower** [ndlib/bendo#36]
When a signal is received, the server should start shutting down, and then exit.

Which signal? `SIGUSR2`? I'm not sure which is consistent with other daemons.

**Comment by dbrower** [comment]
Look at https://github.com/ndlib/bendo/blob/master/architecture/shutdown.md for thoughts on the exact shutdown sequence.

**Comment by msuhovec** [comment]
I find this one intriguing, so I'm gonna look at it

**Comment by msuhovec** [comment]
Don has addressed this

**Comment by dbrower** [comment]
I tied it to `SIGTERM` and `SIGINT`. If runit doesn't let the server take an arbitrary amount of time to exit after sending those signals, we can add another, say, `SIGUSR2` to also ask the server to exit.

Now, does the server get these signals when it is restarted?
