### ISSUE TITLE
Enhance existing (or create new ) Command Line Tools.

### ISSUE THREAD

**Issue by msuhovec** [ndlib/bendo#40]
To support folks ingesting data

**Comment by dbrower** [comment]
see the following for a first design for the `butil` command line utility.
https://github.com/ndlib/bendo/blob/master/architecture/butil.md

**Comment by msuhovec** [comment]
See Don's Document

https://github.com/ndlib/bendo/blob/master/architecture/butil.md

**Comment by msuhovec** [comment]
will do item validation as part of https://github.com/ndlib/bendo/issues/50
