### ISSUE TITLE
Bendo Reporting

### ISSUE THREAD

**Issue by msuhovec** [ndlib/bendo#43]
# of Items, Storage used (Disk Cache and Tape), breakdown of deposited items by size. I'm sure there are others folks may want to see.

**Comment by dbrower** [comment]
The stats I think would be useful

* total storage used
* total number of items
* histogram of items by size. (logarithmic bucket sizes.)

From the total storage used and total number of items we can figure out rate of change. At this level, we don't have enough information to break into mime type. I see that as a Curate report.

Other possibly useful information
* number of fixity checks (successful / error). GB fixity checked.
* cache hit rate. (maybe just reported as cache hits and cache misses?)???? maybe not.

Would GB in/out throughput be better gathered from the sysadmin metrics?
