### ISSUE TITLE
item name validation for butil

### ISSUE THREAD

**Issue by msuhovec** [ndlib/bendo#50]
A bendo item identifier is any string meeting the following conditions

It is at least 1 character long. (There is no specified maximum length. But we all know there is a practical maximum length. I don't know what that is).
It does not contain a forward slash / or whitespace characters.
It does not contain control characters.
TBD: should all unicode characters be allowed.

see also

https://github.com/ndlib/bendo/blob/master/architecture/butil.md

**Comment by dbrower** [comment]
This is done. Closing.
