### ISSUE TITLE
add version action to bclient

### ISSUE THREAD

**Issue by msuhovec** [ndlib/bendo#61]
bclient version <item> returns, version number, date, and contributor

**Comment by dbrower** [comment]
I see this as having output similar to the following.

    $ bclient history <item id>
    @1 2015-12-04 15:56:47 curate_batch "Import"
    @2 2015-12-05 06:00:04 curate            ""
    @3 2015-12-06 12:57:13 curate            ""

I see the main user being a person who is investigating a particular item. The fields displayed should be the information contained in the version table. Perhaps we will add more summary data in the future (e.g. number of files added/changed, etc).

**Comment by msuhovec** [comment]
That looks pretty straightforward.

**Comment by msuhovec** [comment]
OK- it looks like this:

bash-3.2$ ./bclient history id9003x .
@01 2016-01-16T22:02:36.57039724-05:00 nobody ""
@02 2016-01-16T22:04:31.029994253-05:00 nobody ""
@03 2016-01-26T17:24:47.002090385-05:00 nobody ""
@04 2016-01-27T11:40:47.048530727-05:00 nobody ""
@05 2016-01-27T13:26:14.986337855-05:00 nobody ""
@06 2016-01-28T15:01:09.370111548-05:00 nobody ""

**Comment by msuhovec** [comment]
Made it prettier.

 ./bclient history id9003x .
@01 2016-01-16 22:02:36 nobody ""
@02 2016-01-16 22:04:31 nobody ""
@03 2016-01-26 17:24:47 nobody ""
@04 2016-01-27 11:40:47 nobody ""
@05 2016-01-27 13:26:14 nobody ""
@06 2016-01-28 15:01:09 nobody ""
