### ISSUE TITLE
Make fixity web pages

### ISSUE THREAD

**Issue by dbrower** [ndlib/bendo#64]
There needs to be a way to display fixity status information. I envision a unique id field added to each fixity record and the following routes

```
GET /fixity
```

parameters `start` defaults to midnight today, `end` defaults to midnight tomorrow. display all fixity records with a scheduled time in the given range. Other sort parameters: `item=` only display records with the given item id, `status=` only display records with the given status id.

The start or end value of `*` gives an open ended range.

```
GET /fixity/:id
```

return the information for a given fixity record.

```
POST /fixity
```

Create a new fixity record. data in parameters can be `item`, the item to be checked, `when` the time of the scheduled check. defaults to now.

```
PUT /fixity/:id
```

Update a given fixity record. parameters can be `when` so long as the record still has a status of "scheduled".

```
DELETE /fixity/:id
```

can only be deleted if the time is in the future and the record has a status of "scheduled"

A fixity record has the following fields

```
id: the record's id number
item: the item the record is about
when: when the fixity happened or is scheduled to happen
status: one of "scheduled" or "error" or "mismatch"
notes: contains more details for errors and mismatches.
```

**Comment by dbrower** [comment]
This issue seems related to #44.

**Comment by dbrower** [comment]
Notes from #44: 
>[There should be] a web interface which shows all fixity errors sorted from most recent to least recent. The web interface also allows for adding that item to be rechecked.

>I would like just enough interface so that we could write a cron job to poll and send emails on error. I don't want bendo sending emails---that would make its configuration too difficult.

**Comment by jeremyf** [comment]
As this is designed, it would be useful to consider JSON-API as the data structure http://jsonapi.org/

[Go library for JSON-API](http://jsonapi.org/implementations/#server-libraries-go)

**Comment by msuhovec** [comment]
Don has several outstanding issues with the SQL queries.
