### ISSUE TITLE
Use Authentication header

### ISSUE THREAD

**Issue by dbrower** [ndlib/bendo#75]
Use the standard authorization header instead of our custom one. (Or support both)

Since we use a token system instead of a username/password system, treat the username as the token, unless it is empty, then treat the password as the token. Authorization continues as usual once the token is extracted.

Look at https://github.com/julienschmidt/httprouter#basic-authentication for an idea on how to implement this.

**Comment by msuhovec** [comment]
Made a tokens on libvirt9 and restarted server:

app       64877    924  8 14:53 ?        00:00:01 /opt/bendo/gocode/bin/bendo -storage /mnt/bendo --cache-dir /mnt/fedora_backup/bendo_cache/staging --mysql bendo:bendoc1Adm1n@tcp(localhost:3306)/bendo_staging --user-tokens /opt/bendo/.tokens

from /opt/bendo/log

016/02/25 14:53:40 Using user token file /opt/bendo/.tokens
bash-3.2$ ./bclient ls id9003x
Access Denied

bash-3.2$ ./bclient -token 128c8cb0925229d0db1f402902be7588 ls id9003x
id9003x/Main.go
id9003x/bclient
id9003x/bserver/bendoapi.go
id9003x/bserver/bserver.go
id9003x/bserver/bserver.goFiles
id9003x/bserver/chunkfile.go
id9003x/fileutil/.filelist.go.swp
id9003x/fileutil/filelist.go
id9003x/fileutil/fileutil.go
id9003x/main.go

woohoo!

**Comment by msuhovec** [comment]
I guess something we should discuss would be how the tokens file is put in place.

My first thoughts:

- the file location is a hiera variable ( /opt/bendo/.tokens ?)

- the file itself is in the secrets repo

- an additional jenkins build step will get the tokens file for the environment desired, and install it in the location desired.

I, of course, would be delighted by something less mundane.

**Comment by dbrower** [comment]
Yeah. I thought last summer we decided to do all configuration via hiera and not the secrets repo. This is a case where it might be easier to use secrets repo? My question about using arrays in hiera comes from this---we need to track 1) user name, 2) auth level, and 3) its token. That is a lot of information!

I'm unsure of making it a hidden dot file...I think that would be too hard to overlook the existence of the file on the server and make troubleshooting harder.

**Comment by msuhovec** [comment]
it's /opt/bendo/tokens now- no dot
