### ISSUE TITLE
bclient  flags and help messages

### ISSUE THREAD

**Issue by msuhovec** [ndlib/bendo#79]
Looks like this now:

bash-3.2$ bclient

Usage:

bclient [<flags>] <action> <bendo item number> [file]

Available actions:

    bclient [<flags>] get <item> [file]               get item's files. If none are specified, get them all
    bclient [<flags>] ls <item id> [file]             show details about item's files.
    bclient [<flags>] upload  <item id> <files>       upload a file or directory into an exiting item, or create a new one.
    bclient [<flags>] version <item id>               display item versioning information

    General Flags:

    -fileroot (defaults to current directory)  location to get or put files
    -server   (defaults to bendo-staging.library.nd.edu:14000) server_name:port of bendo server
    -numuploaders (defaults to 2) number of concurrent upload/download threads
    -version ( defaults to latest version: ls & get actions) desired version number

    upload Flags:

    -chunksize    ( defaults to 10) Size (in MB) of chunks bclient will use for upload
    -creator      ( defaults to bclient) owner of upload in bendo
    -numuploaders ( defaults to 2) number of upload threads
    -v            ( defaults to false) Provide verbose upload information for troubleshooting

    ls Flags:

    -longV        ( defaults to false) show blob id, size, date created, and creator of each file in item

    get Flags:
    -stub         (defaults to false)  retreive file tree of item, create zero-length stub for each file

**Comment by msuhovec** [comment]
Done :)

**Comment by dbrower** [comment]
much better than what was there before!
