### ISSUE TITLE
bclient always prefixes directory

### ISSUE THREAD

**Issue by dbrower** [ndlib/bendo#81]
A command like `bclient upload foo` will upload all the files in foo, but they will all have slot names in the form `foo/...`. Maybe this would not be so bad if we could do `bclient upload *` inside a directory, but the command does not accept more than one file name or directory to upload.

This issue will be resolved when there is a way to put a bunch of files into a directory, and upload all of them into the "root" of an item.

**Comment by msuhovec** [comment]
Well, the way I do it is with -root  - is this too awkward?

For example

bash-3.2$ bclient ls id9003x

id9003x/Main.go

id9003x/bclient

id9003x/bserver/bendoapi.go

id9003x/bserver/bserver.go

id9003x/bserver/chunkfile.go

id9003x/fileutil/.filelist.go.swp

id9003x/fileutil/filelist.go

id9003x/fileutil/fileutil.go

id9003x/main.go

I'll get this from the server:

bash-3.2$ bclient get id9003x

which creates a directory id9002x in my current diectory:

drwxr-xr-x    6 msuhovec  1750340273          204 Feb 13 19:42 id9003x

I'll change a file:

echo 'modify this one' > id9003x/bserver/chunkfile.go

then upload the change with this command:

bclient -v -root=id9003x  upload id9003x bserver/chunkfile.go


Files to Upload:

File: bserver/chunkfile.go md5 507755a6668be20c5ee5747bae66bd15

Start Upload of id9003x/bserver/chunkfile.go, size 16, chunkSize 10485760
at 2016-02-13 19:49:51.391460859 -0500 EST

Finished Upload of id9003x/bserver/chunkfile.go in 0.045745873 seconds

Alternatively, I could do this

bclient  -root=id9003x  upload id9003x .

which would walk everything under the id9003x directory, and upload
anything that changed.

Mark Suhovecky

Digital Libraries Data Curation Developer

University of Notre Dame
208 Hesburgh Library
574-631-9269
msuhovec@nd.edu

**Comment by dbrower** [comment]
Hm. Ok. I didn't see that option in the help text. That would take care of my concern. In trying to test it i ran into a bug. I'll make a new issue for that.
