### ISSUE TITLE
bclient not uploading a new item

### ISSUE THREAD

**Issue by dbrower** [ndlib/bendo#82]
I have a local server with no item named `zxcvb` on it. I run the following command

    ./bin/bclient -server localhost:14000 -root fileutil upload zxcvb fileutil/

and get the error

    Nothing to do:
    The vesions of All Files given for upload in item zxcvb
    are already present on the server

I expected the files in the fileutil directory to be uploaded to the item named `zxcvb`.

(I would have included the version of bclient I'm using but I couldn't figure out how to display it.)

**Comment by msuhovec** [comment]
I am able to do this on my box:

bash-3.2$ bclient -root id9003x upload id9003x fileutil/
Start Upload of id9003x/fileutil/filelist.go, size 2371, chunkSize 10485760
at 2016-02-15 11:40:04.215044149 -0500 EST
Finished Upload of id9003x/fileutil/filelist.go in 0.12308869000000001
seconds

**Comment by dbrower** [comment]
I think the problem is that I misunderstood how the `-root` option works. In what I had it was trying to upload the file `fileutil/fileutil`, which didn't exist, so it makes sense that nothing was uploaded. The command line that worked for me is

    ./bin/bclient -server localhost:14000 -root fileutil upload zxcvb .

This will go to the directory `fileutil` and then upload everything in there, `.`.
